### ISSUE TITLE
Issues with Python 3

### ISSUE THREAD

**Issue by HEY-YEH** [libpd/libpd#129]
I'm using Python 3.5.1, and I installed libpd by using "make" & "make install".
When I try to run a sample, I got errors below:

ALSA lib pcm.c:2266:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.rear
ALSA lib pcm.c:2266:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.center_lfe
ALSA lib pcm.c:2266:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.side
ALSA lib pcm_route.c:867:(find_matching_chmap) Found no matching channel map
ALSA lib pcm_route.c:867:(find_matching_chmap) Found no matching channel map
ALSA lib pcm_route.c:867:(find_matching_chmap) Found no matching channel map
ALSA lib pcm_route.c:867:(find_matching_chmap) Found no matching channel map
connect(2) call to /dev/shm/jack-1000/default/jack_0 failed (err=No such file or directory)
attempt to connect to server failed
Traceback (most recent call last):
  File "echo.py", line 20, in <module>
    m = PdManager(ch, ch, sr, 1)
  File "/usr/lib/python3.5/site-packages/pylibpd.py", line 340, in __init__
    self.__outbuf = array.array('h', '\x00\x00' * outch * libpd_blocksize())
TypeError: cannot use a str to initialize an array with typecode 'h'

**Comment by baraa121** [comment]
Were you able to figure it out? I have been struggling with the same thing!

**Comment by HEY-YEH** [comment]
I don't know why I got the errors, I just run "python echo.py". I'm a totaly beginner...

**Comment by danomatika** [comment]
Google search for the first error line:

    ALSA lib pcm.c:2266:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.rear

turns up it's an issue with your ALSA config and probably not with the libpd python wrapper:

http://stackoverflow.com/questions/31603555/unknown-pcm-cards-pcm-rear-pyaudio

**Comment by HEY-YEH** [comment]
Can libpd run fine with Python3? Because I found the examples are written by Python2.

**Comment by danomatika** [comment]
It should. Have you tried taking a current example and updating it for Python 3? We'd love to have Pythin 3 versions of each example if the syntax is that different.

**Comment by danomatika** [comment]
Any luck on this?

**Comment by danomatika** [comment]
Closing due to lack of activity.

**Comment by danomatika** [comment]
This was fixed in the latest commit using the suggestion in #265.
