### ISSUE TITLE
pthreadGC2.dll

### ISSUE THREAD

**Issue by Foldover** [libpd/libpd#155]
Not sure if this really is a good fit for "Issues" as it's more of a "personal problems of inexperienced user"-kind of thing. Feel free to remove this post and point me to other places where it makes more sense to ask these sort of questions.

However, I'm trying to build libpd, under windows, to be used in a java project. Building the 32 bit version works fine, both the fundamental build as well as javabuild. I can use libpd under eclipse and it's all fine and dandy. The 64 bit though, builds without complaints, but I get some from the nativeloader class about a pthreadGC2.dll library that is not found. To be clear, I can't see any errors building in mingw64, it's when trying to load the library in my java-project that an exception gets thrown. I can't find any pthreadGC2.dll in the java-build folder.
The nativeloader class is trying to load pthreadGC2.dll from the .jar file, so maybe I have to adjust the Makefile somewhat? I have no experience with Makefiles whatsoever, so I'm a little lost.

Thank you in advance for your assistance and, again, feel free to point me to more appropriate places to ask these sort of questions.

The java stack trace is pretty uninteresting, but just in case:

> Exception in thread "main" org.puredata.core.NativeLoader$NativeLibraryLoadError: Couldn't find pthreadGC2.dll for this platform windows/x86_64
	at org.puredata.core.NativeLoader.loadLibraryFromJar(NativeLoader.java:114)
	at org.puredata.core.NativeLoader.loadLibrary(NativeLoader.java:100)
	at org.puredata.core.NativeLoader.loadLibrary(NativeLoader.java:91)
	at org.puredata.core.PdBase.<clinit>(PdBase.java:76)
	at PureData.<init>(PureData.java:15)
	at UsingProcessing.main(UsingProcessing.java:17)

**Comment by residuum** [comment]
Maintainer of the C# version here with a little experience in Java.

The problem lies probably in https://github.com/libpd/libpd/blob/master/java/org/puredata/core/PdBase.java#L76

`pthreadGC2.dll` is no longer packaged with MingW32, so while bringing the C# wrapper up to date, I have replaced it with `libwinpthread-1.dll`. 

Try the following changes:
- Change `pthreadGC2` to `libwinpthread-1` or `winpthread-1` 
- Change https://github.com/libpd/libpd/blob/master/java/org/puredata/core/NativeLoader.java to load the dll from the correct folder, i.e. from `libs/mingw32` for 32 bit and `libs/mingw64` for 64 bit

In the end, create a pull request with the changes for libpd and/or document the necessary steps in the wiki.

**Comment by danomatika** [comment]
Pinging @nettoyeurny. Can you check this? Should be a small change, as mentioned.

**Comment by Mongo2** [comment]
I think that did the trick. I am getting another error now that might be unrelated, although in the same class:

> Exception in thread "main" java.lang.UnsatisfiedLinkError: C:\%path_to_temp_folder%\pdnative8112553438084538384.dll: Can't find dependent libraries
	at java.lang.ClassLoader$NativeLibrary.load(Native Method)
	at java.lang.ClassLoader.loadLibrary0(Unknown Source)
	at java.lang.ClassLoader.loadLibrary(Unknown Source)
	at java.lang.Runtime.load0(Unknown Source)
	at java.lang.System.load(Unknown Source)
	at org.puredata.core.NativeLoader.loadLibraryFromJar(NativeLoader.java:141)
	at org.puredata.core.NativeLoader.loadLibrary(NativeLoader.java:103)
	at org.puredata.core.PdBase.<clinit>(PdBase.java:78)
	at PureData.<init>(PureData.java:15)
	at UsingProcessing.main(UsingProcessing.java:17)

**Comment by PvonMoradi** [comment]
@danomatika @Mongo2 @residuum 
I've managed to build a `libpd.jar` in `libs` directory. Then I added *all* jar files in libs directory in a user library in Eclipse. Then, I created a project and added two source files found in `java samples` directory. I am getting this exact same error:
```
Exception in thread "main" org.puredata.core.NativeLoader$NativeLibraryLoadError: Couldn't find pthreadGC2.dll for this platform windows/x86_64
	at org.puredata.core.NativeLoader.loadLibraryFromJar(NativeLoader.java:113)
	at org.puredata.core.NativeLoader.loadLibrary(NativeLoader.java:100)
	at org.puredata.core.NativeLoader.loadLibrary(NativeLoader.java:91)
	at org.puredata.core.PdBase.<clinit>(PdBase.java:76)
	at mePackage.JavaSoundThread.<init>(JavaSoundThread.java:44)
	at mePackage.Playground3.main(Playground3.java:11)
```
Here are the files in my `libs` directory:
[](https://imgur.com/a/pOm0i)
And here are my LibPD user library in Eclipse and the files I've added to it:
[](https://imgur.com/a/cgKsH)

**Comment by danomatika** [comment]
Can you try the changes suggested by @residuum ? If they work for you, we can just go ahead and update the master branch. Thank you for taking the time to work through this as, obviously, some aspects of the Windows java build seem to have gotten a bit hairy over the years.

**Comment by PvonMoradi** [comment]
@danomatika What I've done so far:
1- Added these two lines to `PdBase.java`
`NativeLoader.loadLibrary("mingw32/libwinpthread-1", "windows", "x86");		NativeLoader.loadLibrary("mingw64/libwinpthread-1", "windows", "x86_64");`
2- Manually searched and copied libwinpthread-1.dll from my msys32 directory and pasted it to the corresponding directories here:
`libpd\java-build\org\puredata\core\natives\windows`
So for example `libwinpthread-1.dll` resides here:
`libpd\java-build\org\puredata\core\natives\windows\x86\mingw32`
and other one for 64 bit in its folder

Now I'm getting another error:
```
Exception in thread "main" org.puredata.core.NativeLoader$NativeLibraryLoadError: Couldn't find pdnative.dll for this platform windows/x86_64
	at org.puredata.core.NativeLoader.loadLibraryFromJar(NativeLoader.java:113)
	at org.puredata.core.NativeLoader.loadLibrary(NativeLoader.java:100)
	at org.puredata.core.PdBase.<clinit>(PdBase.java:78)
	at moradi.JavaSoundThread.<init>(JavaSoundThread.java:44)
	at moradi.Playground3.main(Playground3.java:11)
```
Which is reasonable since there is no pdnative.dll in the directory for my 64 bit windows.
I suspected this is so because I've used mingw32 as my gcc and used make with mingw32.
So I've changed my PATH to mingw64 and embarked to `make clean` , `make clean libpd` and `make clean javalib` again hoping it would create a pdnative.dll in windows/x86_64 folder.
Here is the error I'm getting in the process:
```
C:/msys32/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/7.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: Cannot export libpd_set_conca
tenated_printhook: symbol not found
C:/msys32/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/7.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: i386 architecture of input fi
le `libpd_wrapper/util/z_print_util.o' is incompatible with i386:x86-64 output
libpd_wrapper/util/z_print_util.o:z_print_util.c:(.text+0x3a): undefined reference to `_strlen'
libpd_wrapper/util/z_print_util.o:z_print_util.c:(.text+0x75): undefined reference to `_strncat'
libpd_wrapper/util/z_print_util.o:z_print_util.c:(.text+0xad): undefined reference to `_strncat'
collect2.exe: error: ld returned 1 exit status
make: *** [Makefile:163: java-build/org/puredata/core/natives/windows/x86_64//pdnative.dll] Error 1
```

I'm opening a new issue for `make`ing via `mingw64`

**Comment by danomatika** [comment]
Seems like your issue is now related to #169

**Comment by danomatika** [comment]
Closing for now.
