### ISSUE TITLE
pdnative.dll not found

### ISSUE THREAD

**Issue by hansdo** [libpd/libpd#169]
I am not sure if this is an issue or not.
I get the error message that pdnative.dll is not found when I try to open a patch. I also do not find anything named "pdnative", should this be changed to something else in PdBase or is something missing?

Exception in thread "main" org.puredata.core.NativeLoader$NativeLibraryLoadError: Couldn't find pdnative.dll for this platform windows/x86_64
	at org.puredata.core.NativeLoader.loadLibraryFromJar(NativeLoader.java:113)
	at org.puredata.core.NativeLoader.loadLibrary(NativeLoader.java:100)
	at org.puredata.core.PdBase.<clinit>(PdBase.java:80)
	at Main.openFile(Main.java:24)
	at Main.testfunc(Main.java:11)
	at Main.main(Main.java:51)

**Comment by mgsx-dev** [comment]
pdnative.dll file should be in libpd.jar

**Comment by hansdo** [comment]
I have that jar as a referenced library, but it gets the same error.

**Comment by danomatika** [comment]
The error indicates that perhaps pdntive is being found, but it's 32bit instead of the required 64.

**Comment by hansdo** [comment]
OK. I can only find one pdnative.dll in the jar, under the org.puredata.natives.windows.x86.

**Comment by danomatika** [comment]
I don't work with Java much, but looks like the 64 but build is missing a 64 bit pdnative.

**Comment by joebowbeer** [comment]
Do the javatests pass on your build?

(BTW, this reminds me that it might be helpful to setup circleci or travis to run some tests on this repo.)

**Comment by hansdo** [comment]
@danomatika Then I understand why it does not work. Thank you.
@joebowbeer  The build works, it is when I run it the problem is noticed.

**Comment by danomatika** [comment]
>this reminds me that it might be helpful to setup circleci or travis to run some tests on this repo

A Travis file was recently added if you want to look into it...

**Comment by danomatika** [comment]
Any updates on this?

**Comment by danomatika** [comment]
I updated the README on building the libpd Java wrapper, perhaps that is helpful?

**Comment by danomatika** [comment]
Closing due to lack of activity.
