### ISSUE TITLE
Problem in building javalib in win7/64 bit via mingw64

### ISSUE THREAD

**Issue by pvonmoradi** [libpd/libpd#199]
Here is the output of `gcc -v`:
```
C:\Users\Pooya\Documents\GitHub\libpd>gcc -v
Using built-in specs.
COLLECT_GCC=gcc
COLLECT_LTO_WRAPPER=C:/msys32/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/7.2.0/lto-wrapper.exe
Target: x86_64-w64-mingw32
Configured with: ../gcc-7.2.0/configure --prefix=/mingw64 --with-local-prefix=/mingw64/local --build=x86_64-w64-mingw32 --host=x86
_64-w64-mingw32 --target=x86_64-w64-mingw32 --with-native-system-header-dir=/mingw64/x86_64-w64-mingw32/include --libexecdir=/ming
w64/lib --enable-bootstrap --with-arch=x86-64 --with-tune=generic --enable-languages=c,lto,c++,objc,obj-c++,fortran,ada --enable-s
hared --enable-static --enable-libatomic --enable-threads=posix --enable-graphite --enable-fully-dynamic-string --enable-libstdcxx
-time=yes --disable-libstdcxx-pch --disable-libstdcxx-debug --disable-isl-version-check --enable-lto --enable-libgomp --disable-mu
ltilib --enable-checking=release --disable-rpath --disable-win32-registry --disable-nls --disable-werror --disable-symvers --with-
libiconv --with-system-zlib --with-gmp=/mingw64 --with-mpfr=/mingw64 --with-mpc=/mingw64 --with-isl=/mingw64 --with-pkgversion='Re
v1, Built by MSYS2 project' --with-bugurl=https://sourceforge.net/projects/msys2 --with-gnu-as --with-gnu-ld
Thread model: posix
gcc version 7.2.0 (Rev1, Built by MSYS2 project)
```
So I'm using mingw 64 bit version.
When I proceed to `make clean`, `make clean libpd` and `make clean javalib`, I'm getting this error for the last command:
```
C:/msys32/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/7.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: Cannot export libpd_set_conca
tenated_printhook: symbol not found
C:/msys32/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/7.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: i386 architecture of input fi
le `libpd_wrapper/util/z_print_util.o' is incompatible with i386:x86-64 output
libpd_wrapper/util/z_print_util.o:z_print_util.c:(.text+0x3a): undefined reference to `_strlen'
libpd_wrapper/util/z_print_util.o:z_print_util.c:(.text+0x75): undefined reference to `_strncat'
libpd_wrapper/util/z_print_util.o:z_print_util.c:(.text+0xad): undefined reference to `_strncat'
collect2.exe: error: ld returned 1 exit status
make: *** [Makefile:163: java-build/org/puredata/core/natives/windows/x86_64//pdnative.dll] Error 1
```
I'm doing so hoping the procedure would create a `pdnative.dll` in this directory: `libpd\java-build\org\puredata\core\natives\windows\x86_64`
Any help is appreciated

**Comment by danomatika** [comment]
@nettoyeurny etc, anyone testing java builds on Windows?

**Comment by danomatika** [comment]
Any update on this?

**Comment by pvonmoradi** [comment]
@danomatika Leider nicht. I needed libpd for my university thesis. I'm using a simple MediaPlayer at the moment and changing its balance parameter. Maybe I look into fixing this issue in this month.

**Comment by pvonmoradi** [comment]
@mgsx-dev  As I said, I'm using Java on Win7/64 bit, and I couldn't even produce a .jar file to work with. It would be great if you can see into this problem. People seem to suggest that running java-tests should catch any errors....

**Comment by danomatika** [comment]
Also, the following:

~~
C:/msys32/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/7.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: Cannot export libpd_set_conca
tenated_printhook: symbol not found
C:/msys32/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/7.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: i386 architecture of input fi
le `libpd_wrapper/util/z_print_util.o' is incompatible with i386:x86-64 output
~~

indicates some of the .c files were compiled for 32 bit and the linker fails as it may be trying to link both 32 and 64 bit objects together.

**Comment by danomatika** [comment]
As a followup, I just built the javalib for both 32bit and 64 bit on Windows using MSYS and MinGW. I had to fix a couple things but didn't se the same error. In any case, I'll update the readme with instructions.

**Comment by danomatika** [comment]
I updated the README with info on setting up Msys2 with MinGW and building the cshaprlib on Windows. Can y'all test those steps out and we can close the issue if it's working?

**Comment by pvonmoradi** [comment]
@danomatika  
**1-** I have Msys2 setup correctly
**2-** I open mingw64.exe on my Windows 7/64 bit machine
**3-** I check `gcc -v `and `make -v`, here are the results:
```
$ gcc -v
Using built-in specs.
COLLECT_GCC=C:\msys32\mingw64\bin\gcc.exe
COLLECT_LTO_WRAPPER=C:/msys32/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/7.2.0/lto-wrapper.exe
Target: x86_64-w64-mingw32
Configured with: ../gcc-7.2.0/configure --prefix=/mingw64 --with-local-prefix=/mingw64/local --build=x86_64-w64-mingw32 --host=x86_64-w64-mingw32 --target=x86_64-w64-mingw32 --with-native-system-header-dir=/mingw64/x86_64-w64-mingw32/include --libexecdir=/mingw64/lib --enable-bootstrap --with-arch=x86-64 --with-tune=generic --enable-languages=c,lto,c++,objc,obj-c++,fortran,ada --enable-shared --enable-static --enable-libatomic --enable-threads=posix --enable-graphite --enable-fully-dynamic-string --enable-libstdcxx-time=yes --disable-libstdcxx-pch --disable-libstdcxx-debug --disable-isl-version-check --enable-lto --enable-libgomp --disable-multilib --enable-checking=release --disable-rpath --disable-win32-registry --disable-nls --disable-werror --disable-symvers --with-libiconv --with-system-zlib --with-gmp=/mingw64 --with-mpfr=/mingw64 --with-mpc=/mingw64 --with-isl=/mingw64 --with-pkgversion='Rev1, Built by MSYS2 project' --with-bugurl=https://sourceforge.net/projects/msys2 --with-gnu-as --with-gnu-ld
Thread model: posix
gcc version 7.2.0 (Rev1, Built by MSYS2 project)

```
```
$ make -v
GNU Make 4.2.1
Built for i686-pc-msys
Copyright (C) 1988-2016 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
```
**4-** I check `javac -version` but it does not recognize it. So I add my java/bin folder by this code:
`$ export PATH=$PATH:"C/Program Files/Java/jdk1.8.0_144/bin"`
(BTW, your new notes on Windows is problematic, the colon in front of C should be omitted and the whole path should be inside double quotations)
Now `javac -version` return this:
```
$ javac -version
javac 1.8.0_144
```
5- `cd`ed into libpd directory
6- `make`
7- `make javalib`
Here is the error I'm getting:
```
$ make javalib
javac -classpath java java/org/puredata/core/PdBase.java
javah -o jni/z_jni.h -classpath java org.puredata.core.PdBase
gcc -DPD -DHAVE_UNISTD_H -DUSEAPI_DUMMY -I./pure-data/src -I./libpd_wrapper -I./libpd_wrapper/util  -DWINVER=0x502 -DWIN32 -D_WIN32 -DPD_INTERNAL -I"C:\Program Files\Java\jdk1.8.0_144/include" -I"C:\Program Files\Java\jdk1.8.0_144/include/win32" -O3   -c -o libpd_wrapper/util/z_queued.o libpd_wrapper/util/z_queued.c
gcc -DPD -DHAVE_UNISTD_H -DUSEAPI_DUMMY -I./pure-data/src -I./libpd_wrapper -I./libpd_wrapper/util  -DWINVER=0x502 -DWIN32 -D_WIN32 -DPD_INTERNAL -I"C:\Program Files\Java\jdk1.8.0_144/include" -I"C:\Program Files\Java\jdk1.8.0_144/include/win32" -O3   -c -o libpd_wrapper/util/ringbuffer.o libpd_wrapper/util/ringbuffer.c
gcc -DPD -DHAVE_UNISTD_H -DUSEAPI_DUMMY -I./pure-data/src -I./libpd_wrapper -I./libpd_wrapper/util  -DWINVER=0x502 -DWIN32 -D_WIN32 -DPD_INTERNAL -I"C:\Program Files\Java\jdk1.8.0_144/include" -I"C:\Program Files\Java\jdk1.8.0_144/include/win32" -O3   -c -o jni/z_jni_plain.o jni/z_jni_plain.c
mkdir -p java-build/org/puredata/core/natives/windows/x86_64/
gcc -o java-build/org/puredata/core/natives/windows/x86_64//pdnative.dll pure-data/src/d_arithmetic.o pure-data/src/d_array.o pure-data/src/d_ctl.o pure-data/src/d_dac.o pure-data/src/d_delay.o pure-data/src/d_fft.o pure-data/src/d_fft_fftsg.o pure-data/src/d_filter.o pure-data/src/d_global.o pure-data/src/d_math.o pure-data/src/d_misc.o pure-data/src/d_osc.o pure-data/src/d_resample.o pure-data/src/d_soundfile.o pure-data/src/d_ugen.o pure-data/src/g_all_guis.o pure-data/src/g_array.o pure-data/src/g_bang.o pure-data/src/g_canvas.o pure-data/src/g_editor.o pure-data/src/g_graph.o pure-data/src/g_guiconnect.o pure-data/src/g_hdial.o pure-data/src/g_hslider.o pure-data/src/g_io.o pure-data/src/g_mycanvas.o pure-data/src/g_numbox.o pure-data/src/g_readwrite.o pure-data/src/g_rtext.o pure-data/src/g_scalar.o pure-data/src/g_template.o pure-data/src/g_text.o pure-data/src/g_toggle.o pure-data/src/g_traversal.o pure-data/src/g_vdial.o pure-data/src/g_vslider.o pure-data/src/g_vumeter.o pure-data/src/m_atom.o pure-data/src/m_binbuf.o pure-data/src/m_class.o pure-data/src/m_conf.o pure-data/src/m_glob.o pure-data/src/m_memory.o pure-data/src/m_obj.o pure-data/src/m_pd.o pure-data/src/m_sched.o pure-data/src/s_audio.o pure-data/src/s_audio_dummy.o pure-data/src/s_file.o pure-data/src/s_inter.o pure-data/src/s_loader.o pure-data/src/s_main.o pure-data/src/s_path.o pure-data/src/s_print.o pure-data/src/s_utf8.o pure-data/src/x_acoustics.o pure-data/src/x_arithmetic.o pure-data/src/x_array.o pure-data/src/x_connective.o pure-data/src/x_gui.o pure-data/src/x_interface.o pure-data/src/x_list.o pure-data/src/x_midi.o pure-data/src/x_misc.o pure-data/src/x_net.o pure-data/src/x_scalar.o pure-data/src/x_text.o pure-data/src/x_time.o libpd_wrapper/s_libpdmidi.o libpd_wrapper/x_libpdreceive.o libpd_wrapper/z_hooks.o libpd_wrapper/z_libpd.o libpd_wrapper/util/z_print_util.o libpd_wrapper/util/z_queued.o libpd_wrapper/util/ringbuffer.o jni/z_jni_plain.o -lm -lpthread -shared -lws2_32 -lkernel32 -Wl,--kill-at
C:/msys32/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/7.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: Cannot export libpd_set_concatenated_printhook: symbol not found
C:/msys32/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/7.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: i386 architecture of input file `libpd_wrapper/util/z_print_util.o' is incompatible with i386:x86-64 output
libpd_wrapper/util/z_print_util.o:z_print_util.c:(.text+0x3a): undefined reference to `_strlen'
libpd_wrapper/util/z_print_util.o:z_print_util.c:(.text+0x75): undefined reference to `_strncat'
libpd_wrapper/util/z_print_util.o:z_print_util.c:(.text+0xad): undefined reference to `_strncat'
collect2.exe: error: ld returned 1 exit status
make: *** [Makefile:163: java-build/org/puredata/core/natives/windows/x86_64//pdnative.dll] Error 1

```

**Comment by pvonmoradi** [comment]
@danomatika  
The above post was before pull from the repo.
I did a hard reset and pulled the repo again (so I have the most up to date master)
Now, using mingw64.exe, I was able to build a .jar file.
When I open eclipse and run `JavaSoundSample`, I'm getting this runtime error:
```
Exception in thread "main" org.puredata.core.NativeLoader$NativeLibraryLoadError: Couldn't find pthreadGC2.dll for this platform windows/x86_64
	at org.puredata.core.NativeLoader.loadLibraryFromJar(NativeLoader.java:113)
	at org.puredata.core.NativeLoader.loadLibrary(NativeLoader.java:100)
	at org.puredata.core.NativeLoader.loadLibrary(NativeLoader.java:91)
	at org.puredata.core.PdBaseLoader$1.load(PdBaseloader.java:55)
	at org.puredata.core.PdBase.<clinit>(PdBase.java:51)
	at com.noisepages.nettoyeur.libpd.sample.JavaSoundThread.<init>(JavaSoundThread.java:44)
	at com.noisepages.nettoyeur.libpd.sample.JavaSoundSample.main(JavaSoundSample.java:24)

```
Which we've talked about a month ago (some C# guy suggested replacing it with something else, then I changed PdBase according to his suggestions, then I get the PdNative error (this post))
https://github.com/libpd/libpd/issues/155
Were you able to run the sample java project (beside successfully building a 32 and 64 bit .jar file)?

**Comment by danomatika** [comment]
>Were you able to run the sample java project (beside successfully building a 32 and 64 bit .jar file)?

No, I just got it to build.

I think I see the issue: the pthreadGC2.dll was replaced with libwinpthread-1.dll for 32 and 64 bit.

Try changing "pthreadGC2" to "libwinpthread-1" in PdBaseLoader.java then rebuild: https://github.com/libpd/libpd/blob/master/java/org/puredata/core/PdBaseLoader.java#L55

**Comment by pvonmoradi** [comment]
@danomatika, Here is what I did:
**1-** Changed line 55 of `libpd\java\org\puredata\core\PdBaseLoader.java` to 		      `NativeLoader.loadLibrary("libwinpthread-1", "windows");`
**2-** Created an Eclipse project and compiled and tested `libpd\samples\java\com\noisepages\nettoyeur\libpd\sample\JavaSoundSample.java` (with minor teak of `test.pd` address in `openPatch()`
It worked! I can hear something! (which I think means the .jar file is successfully created and running)
**Q1-** What did you change from the previous (2 months ago) commit? Since I remember adding `libwinpthread-1` somewhere but the build still complained about `pdnative.dll` (this issue https://github.com/libpd/libpd/issues/199)
**Q2-** For the javadoc and sources, I just need to attach sources here `libpd\java\org\puredata\core` to my `libpd.jar`, right?

Thanks ! 🐱 💻

**Comment by danomatika** [comment]
Ok, I've updated the library naming and added makefile targets to build javadocs and a source jar: https://github.com/libpd/libpd#building-yourself-1

If everything is working, please close this issue.

**Comment by pvonmoradi** [comment]
Thank you! One more thing, do you know where can I find example projects for using libpd with Java? I want to simply send a float to a simple PD  patch and change the frequency of a sinusoidal wave.

**Comment by danomatika** [comment]
Try samples/java/sound...

enohp ym morf tnes
-----------
Dan Wilcox
danomatika.com
robotcowboy.com
